USE EShop 

--This is a comment
--Get all products
Select * from Product

--Get all products that have categoryid = 10
Select * from Product
Where CategoryId=10

--Get total cost of products listed with categoryid = 10
Select Sum(Cost) from Product
Where CategoryId=10

--Get product name, cost from Product table
Select Name,Cost from Product

--Save above as view
CREATE VIEW vw_Product AS
(Select Name,Cost from Product)

--See the view result
select * from vw_Product

--Get all products that starts with 'S'
Select * from Product
Where Name Like 'S%'

--Get all the products whose 2nd letter is 'a'
Select * from Product
Where Name Like '_a%'

--Get all products whose cost is not equal to 7000
Select * from Product
Where Cost<> 7000

-- Starts with anything that has 'O' in the word and ends with 's'
Select * from Product
Where Name Like '%O%s'

--Select all the products with name as 'Lehenga', 'Barfi', 'Iphone'
Select * from Product
Where Name='Barfi' OR Name='Iphone' OR Name='Lehenga'

--Better technique 
Select * from Product 
Where Name in ('Barfi','Lehenga','Iphone')

--Get all the products having a CategoryId matching a category in ProductCategory table
Select * from Product
Where CategoryId in (Select Id from ProductsCategory)

--Get Customer Name and OrderId for all customers
Select [Name],[OrderId] from Customer, Orders
Where Customer.Id = Orders.CustomerId

--Get total revenue generated by 'Akhs'
--Customer name from customer table
--total cost from product
--orders table conatin customer purchases
Select SUM(Cost) from Orders, Customer, Product
Where Orders.CustomerId= Customer.Id
and Orders.ProductId= Product.Id
and Customer.Name='Akhs'

